### ISSUE TITLE
Duplicate documents posted.

### ISSUE THREAD

**Issue by cheburakshu** [lucidworks/spark-solr#178]
Duplicate documents are posted to SOLR even though _gen_uniq_key_ is false and mode is _overwrite_ . 
I thought it was a bug, but is there a way to set a flag, so that spark-solr or solr can internally compute the document signature and overwrite the same index?

One more issue is the spark-solr never posts the data to server even after 30 mins, if soft commit is not set.

The full code is below.

```

tables = ['piwik_goal']

for table in tables:
    parq = spark.read.parquet('/piwik/{}'.format(table)).withColumnRenamed("location_region","loc_region").withColumnRenamed("config_os_version","os_ver").withColumnRenamed("custom_var_v2","cus_var_v2").withColumnRenamed("deleted","del")
    options = {
        'zkhost' : 'localhost:2181/solr',
        'collection' : table,
        'gen_uniq_key' : 'false', 
	'soft_commit_secs' : '10'
    }
    parq.write.format('solr').options(**options).mode('overwrite').save()

```

**Comment by kiranchitturi** [comment]
there is no difference in Save modes in spark-solr. Both modes do the same thing, index documents to Solr. If the 'id' of the document already exists, then it will overwritten otherwise it will index it as a new document. 

Solr does have de-duplication feature. See https://lucene.apache.org/solr/guide/6_6/de-duplication.html

> One more issue is the spark-solr never posts the data to server even after 30 mins, if soft commit is not set.

It is really not about spark-solr posting the data but about the indexed data being visible for search. Please see One more issue is the spark-solr never posts the data to server even after 30 mins, if soft commit is not set.

the `soft_commit_secs` option just enables the soft commit configuration during indexing. See above blog for more details

**Comment by cheburakshu** [comment]
Thanks Kiran. I figured the id part. and also set the soft commit and it works now. Thanks for you help
