### ISSUE TITLE
SolrCloudUtil not present inside com.lucidworks.spark.util package

### ISSUE THREAD

**Issue by Chandanap99** [lucidworks/spark-solr#50]
In "TestIndexing.scala" SolrCloudUtil class has been used to create a collection. But that class is not present inside package com.lucidworks.spark.util package.

**Comment by kiranchitturi** [comment]
@Chandanap99 Are you referring to this test class https://github.com/lucidworks/spark-solr/blob/master/src/test/scala/com/lucidworks/spark/TestIndexing.scala ?

Since the `SolrCloudUtil` class is our test util class, it is not shipped with the package.

Currently, there are no util methods in the package that help with collection creation. 

If you are on recent versions of SolrCloud, then you could use the Collections API to create the collection https://cwiki.apache.org/confluence/display/solr/Collections+API and then use it with spark-solr code
